# Generated by Django 3.2.7 on 2021-09-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
