# Generated by Django 3.2.7 on 2021-09-24 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jupiter', '0002_award_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='killed_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='jupiter.monster'),
        ),
        migrations.AlterField(
            model_name='character',
            name='kills',
            field=models.ManyToManyField(blank=True, related_name='kills', through='jupiter.CharacterKill', to='jupiter.Monster'),
        ),
    ]
