# Generated by Django 3.2.7 on 2021-09-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jupiter', '0004_alter_characterequipment_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterequipment',
            name='slot',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
