# Generated by Django 3.2.7 on 2021-09-26 00:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jupiter', '0011_auto_20210925_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='uploaded_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 26, 2, 19, 27, 455732)),
        ),
    ]
