# Generated by Django 3.2.7 on 2021-09-28 00:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jupiter', '0013_auto_20210926_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='typ',
        ),
        migrations.AlterField(
            model_name='character',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='character',
            name='mortem_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
