# Generated by Django 3.2.7 on 2021-09-28 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jupiter', '0014_auto_20210928_0227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'get_latest_by': ['-mortem_timestamp'], 'ordering': ['-mortem_timestamp']},
        ),
    ]
