# Generated by Django 3.2.8 on 2021-10-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jupiter', '0018_alter_character_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='fated',
            field=models.BooleanField(default=False),
        ),
    ]
