# Generated by Django 3.2.7 on 2021-09-24 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20210924_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterequipment',
            name='slot',
            field=models.IntegerField(blank=True),
        ),
    ]
