# Generated by Django 3.2.7 on 2021-09-24 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_alter_equipmentperk_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characterequipment',
            options={'ordering': ['character']},
        ),
        migrations.AlterModelOptions(
            name='characterinventory',
            options={'ordering': ['character']},
        ),
        migrations.AlterModelOptions(
            name='characterkill',
            options={'ordering': ['character']},
        ),
        migrations.AlterModelOptions(
            name='characterlocation',
            options={'ordering': ['character', 'order']},
        ),
        migrations.AlterModelOptions(
            name='charactertrait',
            options={'ordering': ['character', 'order']},
        ),
        migrations.AlterModelOptions(
            name='equipmentperk',
            options={'ordering': ['character_equipment']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='characterequipment',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='characterinventory',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='characterkill',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='characterlocation',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='charactertrait',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='equipmentperk',
            order_with_respect_to=None,
        ),
    ]
