# Generated by Django 3.2.5 on 2021-07-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='bgg_link',
            field=models.URLField(default='http://www.asd.com', unique=True),
            preserve_default=False,
        ),
    ]
