# Generated by Django 3.2.5 on 2021-07-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_boardgame_bgg_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
